[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        trading_json_log
    Reserve_Data  On
    Preserve_Key  On

[OUTPUT]
    Name        loki
    Match       *
    Host        loki
    Port        3100
    Labels      job=fluent-bit,environment=local
    Label_Keys  $container_name,$source,$service,$level,$event_type,$session_type,$session_phase,$instrument_id,$timeframe
    Line_Format json
